package com.zookeeper;

public interface ZookeeperConstants {

	String ZOOKEEPER_URL = "localhost:2182";
	
	String ZOOKEEPER_PERSISTENT_NODE_KEY = "/PERSISTENT_NODE";
	
	String ZOOKEEPER_PERSISTENT_NODE_VALUE = "PERSISTENT_NODE_VALUE";
	
	
	String ZOOKEEPER_CHILD_NODE_PARENT = "/PARENT_NODE";
	String ZOOKEEPER_CHILD_NODE_1 = "/PARENT_NODE/CHILD_NODE_1";
	String ZOOKEEPER_CHILD_NODE_2 = "/PARENT_NODE/CHILD_NODE_2";
	
}
